# Generated by Django 5.2.8 on 2025-11-30 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do evento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do evento')),
                ('tipo', models.CharField(choices=[('Palestra', 'Palestra'), ('Oficina', 'Oficina'), ('Webinar', 'Webinar'), ('Outros', 'Outros')], default='Outros', max_length=50)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora de início')),
                ('data_fim', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora de término')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local do evento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
    ]
