# Generated by Django 5.2.8 on 2025-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('resumo', models.CharField(blank=True, max_length=300)),
                ('descricao_completa', models.TextField(blank=True)),
                ('sintomas', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamento', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='conteudos_imagens/')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='conteudos_pdfs/')),
                ('link_referencia', models.URLField(blank=True, max_length=300)),
                ('categoria', models.CharField(choices=[('Genética', 'Genética'), ('Neurológica', 'Neurológica'), ('Metabólica', 'Metabólica'), ('Imunológica', 'Imunológica'), ('Outras', 'Outras')], default='Outras', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
