# Generated by Django 5.2.8 on 2025-11-28 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('data_postagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='Status')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovação')),
                ('aprovado', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Relato',
                'verbose_name_plural': 'Relatos',
                'ordering': ['-data_postagem'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='relatos.relato')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='relatos.relato')),
            ],
            options={
                'verbose_name': 'Curtida',
                'verbose_name_plural': 'Curtidas',
                'unique_together': {('relato', 'usuario')},
            },
        ),
    ]
