# Generated by Django 5.2.8 on 2025-11-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('contato', models.CharField(blank=True, max_length=200)),
                ('site', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ongs_imagens/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
