# Generated by Django 5.2.8 on 2025-11-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='laudo',
            field=models.FileField(blank=True, null=True, upload_to='laudos/'),
        ),
    ]
